#!/bin/sh
#

[ -r /etc/lsb-release ] && . /etc/lsb-release

printf "\n"
# Dark OS 风格配色
DARK_OS_CYAN='\033[38;5;87m'    # 亮青色
DARK_OS_MAGENTA='\033[38;5;207m' # 亮品红
DARK_OS_GREEN='\033[38;5;83m'    # 酸橙绿
DARK_OS_YELLOW='\033[38;5;221m'  # 明黄
DARK_OS_BLUE='\033[38;5;33m'     # 亮蓝
DARK_OS_PURPLE='\033[38;5;99m'   # 紫罗兰
NC='\033[0m' # 重置颜色

# 渐变色标题
echo "${DARK_OS_CYAN}"
echo "======================================================================"
echo "${DARK_OS_GREEN}\t ____                   _         ___    ____  "
echo "${DARK_OS_YELLOW}\t|  _ \    __ _   _ __  | | __    / _ \  / ___| "
echo "${DARK_OS_BLUE}\t| | | |  / _| | | '__| | |/ /   | | | | \___ \ "
echo "${DARK_OS_PURPLE}\t| |_| | | (_| | | |    |   <    | |_| |  ___) |"
echo "${DARK_OS_CYAN}\t|____/   \__,_| |_|    |_|\_\    \___/  |____/ "
echo "${DARK_OS_MAGENTA}                                              "
echo "======================================================================"
echo "${NC}"


if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
printf "\n"
printf "Welcome to %s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
